app-config:
  #尝试重连间隔时间（单位:毫秒）
  interval: 1000
  proxy[0]:
    host: 127.0.0.1
    port: 8080
#  proxy[1]:
#    host: 127.0.0.1
#    port: 8082
  port: 8088
server:
    # WebServer bind port
    port: 9010